<footer class="mt-auto text-white-50">
    <p style="padding-top: 6px;">Design by <a href="https://samszo.univ-paris8.fr/" class="text-white">Samuel Szoniecky</a>
        <a target="_blank" href="https://www.univ-paris8.fr/EA-349-Laboratoire-Paragraphe">
                <img style="height: 40px;" src="<?php echo $this->assetUrl('images/logos/logo-paragraphe-blanc.svg'); ?>" alt="Laboratoire Paragraphe" />
        </a>Template for <a href="https://getbootstrap.com/" class="text-white">Bootstrap</a>, by <a href="https://twitter.com/mdo" class="text-white">@mdo</a>.
    </p>            
</footer>
