<?php
$userBar = $this->userBar();
?>
<header class="mb-auto">
<div>

    <nav class="navbar navbar-expand-lg navbar-dark bg-black">
  <div class="container-fluid">
    <a class="navbar-brand" href="<?php echo $site->siteUrl()."/page/welcome";?>"><div style="height:60px;width:200px;" id="logoMazePetit"></div></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

      <li class="nav-item">
        <a class="nav-link" target="_blank" href="https://www.univ-paris8.fr/EA-349-Laboratoire-Paragraphe">
                <img style="height: 40px;" src="<?php echo $this->assetUrl('images/logos/logo-paragraphe-blanc.svg'); ?>" alt="Laboratoire Paragraphe" />
      </li>

        <li class="nav-item">
            <a class="nav-link" target="_blank" href="https://www.univ-paris8.fr/">
                <img style="height: 40px;" src="<?php echo $this->assetUrl('images/logos/logo-p8-white.svg'); ?>"
                    alt="Université Paris 8" />
            </a>
        </li>
        <li class="nav-item"><a class="nav-link" target="_blank" href="http://eur-artec.fr/"><img style="height: 40px;"
                    src="<?php echo $this->assetUrl('images/logos/ArTeC.png'); ?>" alt="Artec" /></a></li>
        <li class="nav-item"><a class="nav-link" target="_blank" href="https://www.iledefrance.fr/"><img style="height: 40px;"
                    src="<?php echo $this->assetUrl('images/logos/region_ile-de-france.svg'); ?>"
                    alt="Région Ile de France" /></a></li>

      </ul>

      <form class="d-flex">
          <?php echo $userBar;?>
      </form>
    </div>
  </div>
</nav>

</div>
</header>
<script>
  /*
    let mlPetit = new amazelogo({'idCont':'logoMazePetit'
        ,'colorLettre':'#e52414','colorMurLettre':'#e52414'
        //,'colorMur':'alea'
        , 'colorPoint':'none'
        ,'textes':['polemika']});
  */
</script>