<?php

$translate = $this->plugin('translate');
$idAction = $this->themeSetting('item_action');
$item = $this->api()->read('items', $idAction)->getContent();

?>

<h1><?php echo $item->displayTitle();?></h1>
<p class="lead"><?php echo $item->displayDescription();?></p>
<p class="lead">
    <a href="<?php echo $site->siteUrl()."/page/rapports";?>" class="btn btn-lg btn-secondary fw-bold border-white bg-white">Commencer</a>
</p>

<script>
    //connectGuest();
</script>