<?php

$nav = $site->publicNav();
$container = $nav->getContainer();
$activePage = $nav->findActive($container);

$translate = $this->plugin('translate');
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('description', "Polemika : les olympiades de l'argumentation. Eduquer à l'esprit critique avec L'IA.");

$this->headMeta()->appendName('author', "Samuel Szoniecky");
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');

$this->headTitle("Polemika : les olympiades de l'argumentation")->setSeparator(' · ');

$this->headScript()->appendFile($this->assetUrl('js/d3.V6.min.js'));
$this->headScript()->appendFile($this->assetUrl('js/geoLoc.js'));
$this->headScript()->appendFile($this->assetUrl('js/bootstrap.bundle.min.js'));
$this->headScript()->appendFile($this->assetUrl('js/anime.min.js'));
$this->headScript()->appendFile($this->assetUrl('js/amazelogo.js'));
$this->headScript()->appendFile($this->assetUrl('js/all.js'));//fontawesome
$this->headScript()->appendFile($this->assetUrl('js/jquery-3.6.0.min.js'));
$this->headScript()->appendFile($this->assetUrl('js/polemika.js'));
$this->headScript()->appendFile($this->assetUrl('js/emotionsGeneva.js'));


$this->headLink()->appendStylesheet($this->assetUrl('css/bootstrap.min.css'));
$this->headLink()->appendStylesheet($this->assetUrl('css/cover.css'));
$this->headLink()->appendStylesheet($this->assetUrl('css/polemika.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/user-bar.css', 'Omeka'));

//pour l'autocompletion
$this->headLink(array('rel'  => 'manifest','href' => $this->assetUrl('../manifest.json')));



$this->trigger('view.layout');

?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html')->setAttribute('lang', $this->lang()); ?>
<?php echo $this->htmlElement('html')->setAttribute('class', "h-100"); ?>

    <head>
        <?php echo $this->headMeta(); ?>
        <link rel="shortcut icon" href="<?php echo $this->assetUrl('img/icons/favicon.ico'); ?>" type="image/x-icon" />
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>

    </head>
    <body class="d-flex h-100 text-center text-white bg-dark">
    
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        <?php echo $this->partial('polemika/header-info', ['site'=>$site]);?>
    
      <main class="px-3">

        <?php 
            echo $this->content; 
        ?>            

      </main>
    
      <?php echo $this->partial('polemika/footer');?>

    </div>
    
            
      </body>
    </html>